name: assignment-test
on: 
    push:
        tags-ignore:
            - '*'
        branches:
            - '*'
jobs:
    unit-test:
        container: cuaesd/aesd-autotest:unit-test
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - name: Checkout submodules
            run : git submodule update --init --recursive
          - name: Run unit test
            run: ./unit-test.sh
    full-test:
        container: cuaesd/aesd-autotest:assignment2
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - name: Checkout submodules
            run : git submodule update --init --recursive
          - name: Install AArch64 toolchain
            run : sudo apt-get install -y gcc-aarch64-linux-gnu
          - name: Install Flex
            run : sudo apt-get install -y flex
          - name: Install Bison
            run : sudo apt-get install -y bison
          - name: Run full test
            run: ./full-test.sh
